In [1]:
import numpy as np

In [6]:
a_list = [1, 2, 3, 4, 5]
 
a_np = np.array(a_list)

In [7]:
type(a_np)

numpy.ndarray

In [9]:
type(a_list)

list

In [11]:
a_list = list(range(1, 101))
sum(a_list)

5050

In [15]:
a_np = np.arange(1, 101, dtype=np.int64)
sum(a_np)

5050

In [17]:
a_np = np.linspace(0, 1, 10)
a_np

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
print(np.array([[1,2],[3,4]]))             #2차원 리스트로 2*2 행렬 만들기
print(np.arange(1,11))                     #범위 내 숫자로 1차원 행렬 만들기
print(np.linspace(0, 1, num=10))           #일정 간격으로 범위내 num 갯수만큼 만들기
print(np.empty((3,3), dtype='float32'))    #초기화 하지 않은 3*3 행렬 만들기
print(np.eye(6, dtype='float32'))          #6*6 대각행렬 만들기(대각요소만 1)
print(np.zeros(3, dtype='float32'))        #0으로 초기화 된 1차원 행렬 만들기
print(np.zeros((3,3), dtype='float32'))    #0으로 초기화 된 3*3 행렬 만들기
print(np.zeros((3,3,3), dtype='float32'))  #0으로 초기화 된 3*3*3 행렬 만들기
print(np.ones((3,3), dtype='float32'))     #1로 초기화 된 3*3 행렬 만들기
print(np.full((3,3), 0.5))                 #0.5로 채워진 3*3 행렬 만들기
print(np.random.random((3,3)))             #임의의 값으로 채워진 3*3 행렬 만들기

[[1 2]
 [3 4]]
[ 1  2  3  4  5  6  7  8  9 10]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0.0000000e+00 1.4012985e-45 0.0000000e+00]
 [7.8061461e-39 1.0369609e-42 0.0000000e+00]
 [1.0761972e-42 1.0089349e-43 1.0102071e-38]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.6521128  0.23053283 0.4686614 ]
 [0.69820967 0.64700954 0.36429985]
 [0.88488891 0.21006006 0.39241187]]


In [20]:
a_np = np.random.random(10)
a_np

In [25]:
a_np.shape
(10,)

(10,)

In [23]:
a_np = a_np.reshape((2,5)) 
a_np

array([[0.03526926, 0.09841804, 0.30539262, 0.93384731, 0.88536816],
       [0.05966313, 0.65313326, 0.70485198, 0.28892811, 0.03617629]])

In [24]:
a_np.shape

(2, 5)

In [26]:
a_np = np.arange(10)
#array[start : stop : step]
print(a_np)         #[0 1 2 3 4 5 6 7 8 9]
print(a_np[3:])     #      [3 4 5 6 7 8 9]
print(a_np[:3])     #[0 1 2]
print(a_np[2:-3])   #    [2 3 4 5 6]
print(a_np[::2])    #[0 2 4 6 8] 
print(a_np[-1::-2]) #[9 7 5 3 1]

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]
[9 7 5 3 1]


In [27]:
a_np = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a_np)
print(a_np[0,:3])   #row : 0,   col : 0~3
print(a_np[:,1:-2]) #row : all, col : 1~2
print(a_np[1,:])    #row : 1,   col : all

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3]
[[2 3]
 [7 8]]
[ 6  7  8  9 10]


In [28]:
a_np = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a_np * 5)
print(a_np / 5)
print(a_np ** 5)
print(a_np % 5)
print(a_np // 5)
print(a_np + a_np)
print(a_np * a_np)
print(a_np ** a_np)

[[ 5 10 15 20 25]
 [30 35 40 45 50]]
[[0.2 0.4 0.6 0.8 1. ]
 [1.2 1.4 1.6 1.8 2. ]]
[[     1     32    243   1024   3125]
 [  7776  16807  32768  59049 100000]]
[[1 2 3 4 0]
 [1 2 3 4 0]]
[[0 0 0 0 1]
 [1 1 1 1 2]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]
[[         1          4         27        256       3125]
 [     46656     823543   16777216  387420489 1410065408]]


In [29]:
from time import time

start = time()
#1~1000000까지 더하기 - 일반 리스트 사용
a_list = list(range(1, 1_000_001))
print('sum : ', sum(a_list))
end = time()

print('calc time : {}'.format(end-start))

start = time()
#1~1000000까지 더하기 - numpy 사용
a_np = np.arange(1, 1_000_001, dtype=np.int64)
print('sum : ', a_np.sum())
end = time()

print('calc time : {}'.format(end-start))

sum :  500000500000
calc time : 0.030507564544677734
sum :  500000500000
calc time : 0.003004312515258789


In [31]:
import numpy as np

# 배열 정의
a_np = np.array([[1, 2, 3], [4, 5, 6]])
b_np = np.array([[1, 3, 5], [2, 4, 6]])

# 조건 비교와 인덱스 찾기 함수 실습
r1 = np.any(a_np > 3)          # 배열에 3보다 큰 요소가 하나라도 있으면 True
print("r1:", r1)

r2 = np.all(a_np > 3)          # 모든 요소가 3보다 크면 True, 아니면 False
print("r2:", r2)

r3 = a_np >= b_np              # 요소별로 a_np가 b_np보다 크거나 같은지 비교
print("r3:\n", r3)

r4 = a_np[a_np >= b_np]        # a_np에서 조건(r3)을 만족하는 값만 추출
print("r4:", r4)

r5 = np.where(a_np > 2)        # 2보다 큰 요소의 인덱스를 반환 (행, 열 배열 쌍)
print("r5:", r5)

r6 = np.where(a_np > 2, a_np, 0)  # 2보다 크면 a_np 값, 아니면 0으로 채움
print("r6:\n", r6)

r7 = np.where(a_np > 2, a_np*2, 1)  # 2보다 크면 a_np*2, 아니면 1로 채움
print("r7:\n", r7)

r8 = np.argmax(a_np)           # 배열 전체에서 최대값의 인덱스 (평평한 1D 기준)
print("r8:", r8)

r9 = np.argmax(a_np, axis=1)   # 행별 최대값의 인덱스
print("r9:", r9)

r10 = np.argmax(a_np, axis=0)  # 열별 최대값의 인덱스
print("r10:", r10)

r1: True
r2: False
r3:
 [[ True False False]
 [ True  True  True]]
r4: [1 4 5 6]
r5: (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))
r6:
 [[0 0 3]
 [4 5 6]]
r7:
 [[ 1  1  6]
 [ 8 10 12]]
r8: 5
r9: [2 2]
r10: [1 1 1]
